capstone/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('conc.urls')),
    path('common/', include('common.urls')),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

conc/urls.py
from django.urls import path
from . import views

app_name = 'conc'
urlpatterns = [
    path('', views.index, name='index'),
    path('project/', views.project, name='project'),
    path('detect/', views.detect, name='detect'),
    path('result/', views.result, name='result'),
    path('mypage/', views.mypage.as_view(), name='mypage'),
]

common/models.py
from django.db import models

# Create your models here.

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    last_name = forms.CharField(label="성")
    first_name = forms.CharField(label="이름")
    class Meta:
        model = User
        fields = ("username", "password1", "password2", "last_name", "first_name")

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('conc:index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

common/templates/common/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger" role="alert">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger" role="alert">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

common/templates/common/login.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta content="IE=edge" http-equiv="X-UA-Compatible">
  <meta content="width=device-width,initial-scale=1" name="viewport">
  <meta content="description" name="description">
  <meta name="google" content="notranslate" />
  <meta content="Mashup templates have been developped by Orson.io team" name="author">

  <!-- Disable tap highlight on IE -->
  <meta name="msapplication-tap-highlight" content="no">
  
  
  <link rel="apple-touch-icon" sizes="180x180" href="../../../static/images/apple-icon-180x180.png">
  <link href="../../../static/images/favicon.ico" rel="icon">

  <link href="" rel="stylesheet">


  <title>어디보냐</title>

<link href="../../../static/style.css" rel="stylesheet"></head>

<body> <!-- Add your content of header -->
<header>
  <nav class="navbar navbar-default active">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'conc:index' %}" title="">
          <img src="../../../static/images/mashup-icon.svg" class="navbar-logo-img" alt="">
          어디보냐
        </a>
      </div>
    </div>
  </nav>
</header>

<!-- Add your site or app content here -->
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-6 col-md-offset-3">
        <br>
        <h1 class="text-center">어디보냐</h1>
        <br>
        <table class="table table-bordered">
          <tr><td>
            <br>
            <form method="post" action="{% url 'common:login' %}">
              {% csrf_token %}
              {% include "./form_errors.html" %}
              <div class="form-group">
                <label for="username">사용자ID</label>
                <input type="text" class="form-control" name="username" id="username" placeholder="아이디"
                        value="{{form.username.value|default_if_none:''}}">
              </div>
              <div class="form-group">
                <label for="password">비밀번호</label>
                <input type="password" class="form-control" name="password" id="password" placeholder="비밀번호"
                        value="{{form.password.value|default_if_none:''}}">
              </div>
              <div class="text-center">
                <button type="submit" class="btn btn-primary">로그인</button>
              </div>
            </form>
            <br>
          </td></tr>
        </table>
        <div class="text-center">
          <span>또는 <a href="{% url 'common:signup' %}">계정을 만드세요.</a></span>
        </div>
        <br><br><br><br><br>
      </div>
    </div>
  </div>

<footer class="footer-container white-text-container">
  <div class="container">
    <div class="row">

     
      <div class="col-xs-12">
        <h3>INUIT</h3>

        <div class="row">
          <div class="col-xs-12 col-sm-7">
            <p><small>Capstone Design (2021-2022)</small>
            </p>
            <p><small>Website created with <a href="http://www.mashup-template.com/" title="Create website with free html template">Mashup Template</a>/<a href="https://www.unsplash.com/" title="Beautiful Free Images">Unsplash</a></small>
            </p>
          </div>
        </div>
        
      </div>
    </div>
  </div>
</footer>

<script>
  document.addEventListener("DOMContentLoaded", function (event) {
    navActivePage();
    scrollRevelation('.reveal');
  });
</script>

<!-- Google Analytics: change UA-XXXXX-X to be your site's ID 

<script>
  (function (i, s, o, g, r, a, m) {
    i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
      (i[r].q = i[r].q || []).push(arguments)
    }, i[r].l = 1 * new Date(); a = s.createElement(o),
      m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
  })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
  ga('create', 'UA-XXXXX-X', 'auto');
  ga('send', 'pageview');
</script>

--> <script type="text/javascript" src="../../../static/main.js"></script></body>

</html>

common/templates/common/signup.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta content="IE=edge" http-equiv="X-UA-Compatible">
  <meta content="width=device-width,initial-scale=1" name="viewport">
  <meta content="description" name="description">
  <meta name="google" content="notranslate" />
  <meta content="Mashup templates have been developped by Orson.io team" name="author">

  <!-- Disable tap highlight on IE -->
  <meta name="msapplication-tap-highlight" content="no">
  
  
  <link rel="apple-touch-icon" sizes="180x180" href="../../../static/images/apple-icon-180x180.png">
  <link href="../../../static/images/favicon.ico" rel="icon">

  <link href="" rel="stylesheet">


  <title>어디보냐</title>

<link href="../../../static/style.css" rel="stylesheet"></head>

<body> <!-- Add your content of header -->
<header>
  <nav class="navbar navbar-default active">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'conc:index' %}" title="">
          <img src="../../../static/images/mashup-icon.svg" class="navbar-logo-img" alt="">
          어디보냐
        </a>
      </div>


    </div>
  </nav>
</header>

<!-- Add your site or app content here -->
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-6 col-md-offset-3">
        <h1 class="text-center">어디보냐</h1>
          <form method="post" class="post-form" action="{% url 'common:signup' %}">
              {% csrf_token %}
              {% include "./form_errors.html" %}
              <div class="form-group">
                  <label for="username">아이디</label>
                  <input type="text" class="form-control" name="username" id="username"
                          value="{{ form.username.value|default_if_none:'' }}">
              </div>
              <div class="form-group">
                  <label for="password1">비밀번호</label>
                  <input type="password" class="form-control" name="password1" id="password1"
                          value="{{ form.password1.value|default_if_none:'' }}">
              </div>
              <div class="form-group">
                  <label for="password2">비밀번호 확인</label>
                  <input type="password" class="form-control" name="password2" id="password2"
                          value="{{ form.password2.value|default_if_none:'' }}">
              </div>
              <div class="form-group">
                  <label for="last_name">성</label>
                  <input type="text" class="form-control" name="last_name" id="last_name"
                          value="{{ form.last_name.value|default_if_none:'' }}">
              </div>
              <div class="form-group">
                  <label for="first_name">이름</label>
                  <input type="text" class="form-control" name="first_name" id="first_name"
                          value="{{ form.first_name.value|default_if_none:'' }}">
              </div>
              <div class="text-center">
                <button type="submit" class="btn btn-primary btn-lg">가입하기</button>
              </div>
          </form>
      </div>
    </div>
  </div>

<footer class="footer-container white-text-container">
  <div class="container">
    <div class="row">

     
      <div class="col-xs-12">
        <h3>INUIT</h3>

        <div class="row">
          <div class="col-xs-12 col-sm-7">
            <p><small>Capstone Design (2021-2022)</small>
            </p>
              <p><small>Website created with <a href="http://www.mashup-template.com/" title="Create website with free html template">Mashup Template</a>/<a href="https://www.unsplash.com/" title="Beautiful Free Images">Unsplash</a></small>
            </p>
          </div>
        </div>
        
        
      </div>
    </div>
  </div>
</footer>

<script>
  document.addEventListener("DOMContentLoaded", function (event) {
    navActivePage();
    scrollRevelation('.reveal');
  });
</script>

<!-- Google Analytics: change UA-XXXXX-X to be your site's ID 

<script>
  (function (i, s, o, g, r, a, m) {
    i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
      (i[r].q = i[r].q || []).push(arguments)
    }, i[r].l = 1 * new Date(); a = s.createElement(o),
      m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
  })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
  ga('create', 'UA-XXXXX-X', 'auto');
  ga('send', 'pageview');
</script>

--> <script type="text/javascript" src="../../../static/main.js"></script></body>

</html>