capstone/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('conc.urls')),
    path('common/', include('common.urls')),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

conc/urls.py
from django.urls import path
from . import views

app_name = 'conc'
urlpatterns = [
    path('', views.index, name='index'),
    path('project/', views.project, name='project'),
    path('detect/', views.detect, name='detect'),
    path('result/', views.result, name='result'),
    path('mypage/', views.mypage.as_view(), name='mypage'),
]

conc/models.py
from django.db import models
from django.contrib.auth.models import User

class TempScore(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.IntegerField()
    time = models.DateTimeField(auto_now_add=True)

class History(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    avg_score = models.IntegerField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    duration = models.IntegerField()

conc/views.py
from django.views.decorators import gzip
from django.views import generic
from django.shortcuts import render, redirect
from django.http import StreamingHttpResponse, HttpResponse, HttpResponseRedirect
from .models import TempScore, History
from django.utils.safestring import mark_safe
from datetime import date, datetime, timedelta
from .utils import Calendar
import calendar

#모델 경로 관련
import os

#opencv&tensorflow
import cvlib as cv
import cv2
import numpy as np
from tensorflow.keras.models import load_model
from tensorflow.keras.applications.resnet50 import preprocess_input
from tensorflow.keras.preprocessing.image import img_to_array
from PIL import ImageFont, ImageDraw, Image
#import threading

from time import mktime, strptime

import json

def index(request):
    if request.user.is_authenticated: #유저가 로그인 되어 있으면,
        return redirect('conc:mypage') #mypage로 redirect
    return render(request, 'conc/index.html') #로그인 되어있지 않으면 index.html을 렌더링

class mypage(generic.ListView):
    model = History
    template_name = 'conc/mypage.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        d = get_date(self.request.GET.get('month', None))

        cal = Calendar(d.year, d.month)

        html_cal = cal.formatmonth(self.request.user, withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

def project(request):
    if not request.user.is_authenticated: #유저가 로그인 되어있지 않으면,
        return redirect('common:login') #login 페이지로 redirect
    if request.method == "POST":
        return redirect('conc:result')
    return render(request, 'conc/project.html')

def result(request):
    stocks = TempScore.objects.filter(user=request.user).order_by('time')

    if len(stocks) == 0:
        return render(request, 'conc/result_error.html')

    score_list = []
    dt = stocks[0].time
    score = 0
    count = 0
    for stock in stocks:
        if dt.minute == stock.time.minute and dt.hour == stock.time.hour and dt.date() == stock.time.date():
            score += stock.score
            count += 1
            continue

        avg_score = score // count
        time_tuple = strptime(str(dt), '%Y-%m-%d %H:%M:%S.%f')
        utc_now = mktime(time_tuple) * 1000
        score_list.append([utc_now, avg_score])

        dt = stock.time
        score = stock.score
        count = 1

    avg_score = score // count
    time_tuple = strptime(str(dt), '%Y-%m-%d %H:%M:%S.%f')
    utc_now = mktime(time_tuple) * 1000
    score_list.append([utc_now, avg_score])

    score_by_minute = np.array(score_list)[:,1]
    total_avg_score = int(score_by_minute.mean())

    timediff = stocks[len(stocks)-1].time - stocks[0].time
    history = History(user=request.user, avg_score=total_avg_score, start_time=stocks[0].time, end_time=stocks[len(stocks)-1].time, duration=timediff.seconds//60)
    history.save() #History에 전체 평균 점수 저장
    stocks.delete() #TempScore에 저장된 기록 삭제

    scoreJson = json.dumps(score_list)
    data = {
        'score': scoreJson,
    }

    return render(request, 'conc/result.html', data)

class VideoCamera(object):
    def __init__(self):
        self.model = load_model(os.path.join(os.path.dirname(__file__),"..") + '/static/model.h5')
        self.video = cv2.VideoCapture(0)
        #(self.status, self.frame) = self.video.read()
        #threading.Thread(target=self.update, args=()).start()
        
    def __del__(self):
        self.video.release()

    def get_frame(self, user):
        (self.status, self.frame) = self.video.read()
        
        if (not self.status):
            self.video = cv2.VideoCapture(0)
            return False
        image = self.frame
        face, confidence = cv.detect_face(image)
        for idx, f in enumerate(face):
            (startX, startY) = f[0], f[1]
            (endX, endY) = f[2], f[3]
            if 0 <= startX <= image.shape[1] and 0 <= endX <= image.shape[1] and 0 <= startY <= image.shape[0] and 0 <= endY <= image.shape[0]:
                    face_region = image[startY:endY, startX:endX]
                    face_region1 = cv2.resize(face_region, (224, 224), interpolation=cv2.INTER_AREA)
                    x = img_to_array(face_region1)
                    x = np.expand_dims(x, axis=0)
                    x = preprocess_input(x)
                    prediction = self.model.predict(x)
                    
                    if prediction < 0.5:
                        score = TempScore(user=user, score=100)
                        score.save()
                        cv2.rectangle(image, (startX, startY), (endX, endY), (0,255,0), 2)
                        Y = startY - 10 if startY - 10 > 10 else startY + 10
                        text = "Concentrate ({:.2f}%)".format((1 - prediction[0][0])*100)
                        cv2.putText(image, text, (startX, Y), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0,255,0), 2)
                    else:
                        score = TempScore(user=user, score=0)
                        score.save()
                        cv2.rectangle(image, (startX, startY), (endX, endY), (0,0,255), 2)
                        Y = startY - 10 if startY - 10 > 10 else startY + 10
                        text = "No concentrate ({:.2f}%)".format(prediction[0][0]*100)
                        cv2.putText(image, text, (startX, Y), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0,0,255), 2)
        
        _, jpeg = cv2.imencode('.jpg', image)
        return jpeg.tobytes()

    '''
    def update(self):
        while True:
            (self.status, self.frame) = self.video.read()
    '''

def gen(camera, user):
    while True:
        frame = camera.get_frame(user)
        if (not frame):
            continue
        yield(b'--frame\r\n'
              b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')

@gzip.gzip_page        
def detect(request):
    try:
        cam = VideoCamera()
        return StreamingHttpResponse(gen(cam, request.user), content_type="multipart/x-mixed-replace;boundary=frame")
    except:
        print("error")
        pass

conc/templates/conc/mypage.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta content="IE=edge" http-equiv="X-UA-Compatible">
  <meta content="width=device-width,initial-scale=1" name="viewport">
  <meta content="description" name="description">
  <meta name="google" content="notranslate" />
  <meta content="Mashup templates have been developped by Orson.io team" name="author">

  <!-- Disable tap highlight on IE -->
  <meta name="msapplication-tap-highlight" content="no">
  
  
  <link rel="apple-touch-icon" sizes="180x180" href="../../../static/images/apple-icon-180x180.png">
  <link href="../../../static/images/favicon.ico" rel="icon">

  <link href="" rel="stylesheet">


  <title>어디보냐</title>

<link href="../../../static/calendar.css" rel="stylesheet">
<link href="../../../static/style.css" rel="stylesheet"></head>

<body> <!-- Add your content of header -->
<header>
  <nav class="navbar navbar-default active">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'conc:index' %}" title="">
          <img src="../../../static/images/mashup-icon.svg" class="navbar-logo-img" alt="">
          aTTeTion DeTecTor
        </a>
      </div>

      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'conc:index' %}" title="">Home</a></li>
          <li><a href="{% url 'conc:project' %}" title="">집중도 측정</a></li>
          <li>
            <p>
              <a href="{% url 'common:logout' %}" class="btn btn-default navbar-btn" title="">로그아웃</a>
            </p>
          </li>

        </ul>
      </div> 
    </div>
  </nav>
</header>

<div class="section-container">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-md-8 col-md-offset-2">
          <h1 class="text-center">나의 학습이력</h1>
          <br>
          <div class="clearfix">
            <a class="btn btn-info left" href="{% url 'conc:mypage' %}?{{ prev_month }}"> 이전 </a>
            <a class="btn btn-info right" href="{% url 'conc:mypage' %}?{{ next_month }}"> 다음 </a>
          </div>
          {{ calendar }}
       </div>
      </div>
    </div>
  </div>





<footer class="footer-container white-text-container">
  <div class="container">
    <div class="row">    
      <div class="col-xs-12">
        <h3>INUIT</h3>
        <div class="row">
          <div class="col-xs-12 col-sm-7">
            <p><small>Capstone Design (2021-2022)</small>
            </p>
            <p><small>Website created with <a href="http://www.mashup-template.com/" title="Create website with free html template">Mashup Template</a>/<a href="https://www.unsplash.com/" title="Beautiful Free Images">Unsplash</a></small>
            </p>
          </div>
        </div>       
      </div>
    </div>
  </div>
</footer>

<script>
  document.addEventListener("DOMContentLoaded", function (event) {
    navActivePage();
    scrollRevelation('.reveal');
  });
</script>

<!-- Google Analytics: change UA-XXXXX-X to be your site's ID 

<script>
  (function (i, s, o, g, r, a, m) {
    i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
      (i[r].q = i[r].q || []).push(arguments)
    }, i[r].l = 1 * new Date(); a = s.createElement(o),
      m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
  })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
  ga('create', 'UA-XXXXX-X', 'auto');
  ga('send', 'pageview');
</script>

--> <script type="text/javascript" src="../../../static/main.js"></script></body>

</html>

conc/templates/conc/project.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta content="IE=edge" http-equiv="X-UA-Compatible">
  <meta content="width=device-width,initial-scale=1" name="viewport">
  <meta content="description" name="description">
  <meta name="google" content="notranslate" />
  <meta content="Mashup templates have been developped by Orson.io team" name="author">

  <!-- Disable tap highlight on IE -->
  <meta name="msapplication-tap-highlight" content="no">
  
  
  <link rel="apple-touch-icon" sizes="180x180" href="../../../static/images/apple-icon-180x180.png">
  <link href="../../../static/images/favicon.ico" rel="icon">

  <link href="" rel="stylesheet">


  <title>어디보냐</title>

<link href="../../../static/style.css" rel="stylesheet"></head>

<body> <!-- Add your content of header -->
<header>
  <nav class="navbar navbar-default active">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
    </div>
  </nav>
</header>

<div class="section-container">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-md-8 col-md-offset-2">
          <h1 class="text-center">집중도 측정하기</h1>
        
          <div class="row">
            <div id="btndiv" class="col-xs-2 col-xs-offset-4">
              <button id="playPauseBtn" class="btn btn-primary">시작</button>
            </div>
            <div class="col-xs-2">
              <form id="frm" method="post" class="post-form" action="{% url 'conc:project' %}">
                {% csrf_token %}
                <input type="button" value="정지" id="stop" onclick="button_event();" class="btn btn-primary">
              </form>
            </div>
          </div>
          <div class="text-center">  
            <b id="wait"><br><br><br><br><br><br>측정을 시작하려면 시작버튼을 눌러주세요<br><br><br><br><br><br></b>
          </div>
          <br>  
          <img id="demo" src="" alt="" style="width:750px;" />
       </div>
      </div>
    </div>
  </div>

<footer class="footer-container white-text-container">
  <div class="container">
    <div class="row">

     
      <div class="col-xs-12">
        <h3>INUIT</h3>

        <div class="row">
          <div class="col-xs-12 col-sm-7">
            <p><small>Capstone Design (2021-2022)</small>
            </p>
            <p><small>Website created with Mashup Template/Unsplash</small>
            </p>
            <p><small>asdfas, CC BY-SA 4.0, via Wikimedia Commons</small>
            </p>
          </div>
        </div>
        
        
      </div>
    </div>
  </div>
</footer>


<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>


<script type="text/javascript">
  $(document).on('click', '#playPauseBtn', function() {
    var isPlaying = $(this).hasClass('pause');

    if(isPlaying){
      video_off();
      $(this).toggleClass('pause');
      $("#btndiv").toggleClass('col-xs-offset-5');
      $("#btndiv").toggleClass('col-xs-offset-4');
      document.getElementById("playPauseBtn").innerHTML = "시작";
      $("#stop").show();
    }
    else{
      video_on();
      $(this).toggleClass('pause');
      $("#btndiv").toggleClass('col-xs-offset-4');
      $("#btndiv").toggleClass('col-xs-offset-5');
      document.getElementById("playPauseBtn").innerHTML = "일시정지";
      $("#stop").hide();
    }
  });
  function video_on(){
    document.getElementById("wait").innerHTML = "";
    document.getElementById("demo").src = "../../../static/images/Loader.gif";
    setTimeout(load_video, 0);
  }
  function load_video(){
    document.getElementById("demo").src = "{% url 'conc:detect' %}";
  }
  function video_off() {
    document.getElementById("demo").src = "";
    document.getElementById("wait").innerHTML = "<br><br><br><br><br>측정을 시작하려면 시작버튼을 눌러주세요<br><br><br><br><br>";
  }
  function button_event(){
    if(confirm("학습을 종료하시겠습니까?")==true){
      document.getElementById("frm").submit();
    }else{
      return;
    }
  }
</script>

<script>
  document.addEventListener("DOMContentLoaded", function (event) {
    navActivePage();
    scrollRevelation('.reveal');
  });
</script>

<!-- Google Analytics: change UA-XXXXX-X to be your site's ID 

<script>
  (function (i, s, o, g, r, a, m) {
    i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
      (i[r].q = i[r].q || []).push(arguments)
    }, i[r].l = 1 * new Date(); a = s.createElement(o),
      m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
  })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
  ga('create', 'UA-XXXXX-X', 'auto');
  ga('send', 'pageview');
</script>

--> <script type="text/javascript" src="../../../static/main.js"></script></body>

</html>

conc/templates/conc/result.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta content="IE=edge" http-equiv="X-UA-Compatible">
  <meta content="width=device-width,initial-scale=1" name="viewport">
  <meta content="description" name="description">
  <meta name="google" content="notranslate" />
  <meta content="Mashup templates have been developped by Orson.io team" name="author">

  <!-- Disable tap highlight on IE -->
  <meta name="msapplication-tap-highlight" content="no">
  
  
  <link rel="apple-touch-icon" sizes="180x180" href="../../../static/images/apple-icon-180x180.png">
  <link href="../../../static/images/favicon.ico" rel="icon">

  <link href="" rel="stylesheet">


  <title>어디보냐</title>

<link href="../../../static/style.css" rel="stylesheet">
<script src="https://code.highcharts.com/highcharts.src.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script></head>

<body> <!-- Add your content of header -->
<header>
  <nav class="navbar navbar-default active">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'conc:index' %}" title="">
          <img src="../../../static/images/mashup-icon.svg" class="navbar-logo-img" alt="">
          어디보냐
        </a>
      </div>

      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'conc:index' %}" title="">Home</a></li>
          <li><a href="{% url 'conc:project' %}" title="">집중도 측정</a></li>
          <li>
            <p>
              <a href="{% url 'common:logout' %}" class="btn btn-default navbar-btn" title="">로그아웃</a>
            </p>
          </li>

        </ul>
      </div> 
    </div>
  </nav>
</header>

<div class="section-container">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-md-8 col-md-offset-2">
          <h1 class="text-center">나의 점수는</h1>
          
          <div id="container">          
            <script>
              var scoreJson = {{score|safe}};

              $(function (){
                Highcharts.setOptions({
                  global: {
                    useUTC: false
                  }
                });

                Highcharts.chart("container", {

                  chart: {
                    type: 'line',
                    height: 500
                  },
                  
                  title: {
                    text: ''
                  },

                  xAxis: {
                    type: 'datetime',
                    labels:{
                      formatter: function(){
                        return Highcharts.dateFormat('%H:%M', this.value);
                      },
                      step: 3
                    }
                  },

                  yAxis: {
                    labels: {
                      format: '{value}',
                      style: {
                        color: 'rgba(0,0,0,.6)',
                      },
                    },
                    opposite: false,
                    tickInterval: 20,
                    max: 100,
                  },

                  tooltip: {
                    xDateFormat: '%H:%M',
                    split: true
                  },

                  series: [{
                      name: '점수',
                      data: scoreJson,
                      color: 'rgba(0,200,0,.6)',
                      lineWidth: 2
                  }],

                  legend: {
                    enabled: true,
                    align: 'left',
                    verticalAlign: 'top',
                    x: 30,
                    y: 70
                  }

                });
              });
            </script>
          </div>

       </div>
      </div>
    </div>
  </div>


<footer class="footer-container white-text-container">
  <div class="container">
    <div class="row">

     
      <div class="col-xs-12">
        <h3>INUIT</h3>

        <div class="row">
          <div class="col-xs-12 col-sm-7">
            <p><small>Capstone Design (2021-2022)</small>
            </p>
            <p><small>Website created with <a href="http://www.mashup-template.com/" title="Create website with free html template">Mashup Template</a>/<a href="https://www.unsplash.com/" title="Beautiful Free Images">Unsplash</a></small>
            </p>
          </div>
        </div>
        
        
      </div>
    </div>
  </div>
</footer>

<script>
  document.addEventListener("DOMContentLoaded", function (event) {
    navActivePage();
    scrollRevelation('.reveal');
  });
</script>

<!-- Google Analytics: change UA-XXXXX-X to be your site's ID 

<script>
  (function (i, s, o, g, r, a, m) {
    i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
      (i[r].q = i[r].q || []).push(arguments)
    }, i[r].l = 1 * new Date(); a = s.createElement(o),
      m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
  })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
  ga('create', 'UA-XXXXX-X', 'auto');
  ga('send', 'pageview');
</script>

--> <script type="text/javascript" src="../../../static/main.js"></script></body>

</html>

conc/templates/conc/result_error.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta content="IE=edge" http-equiv="X-UA-Compatible">
  <meta content="width=device-width,initial-scale=1" name="viewport">
  <meta content="description" name="description">
  <meta name="google" content="notranslate" />
  <meta content="Mashup templates have been developped by Orson.io team" name="author">

  <!-- Disable tap highlight on IE -->
  <meta name="msapplication-tap-highlight" content="no">
  
  
  <link rel="apple-touch-icon" sizes="180x180" href="../../../static/images/apple-icon-180x180.png">
  <link href="../../../static/images/favicon.ico" rel="icon">

  <link href="" rel="stylesheet">


  <title>어디보냐</title>

<link href="../../../static/style.css" rel="stylesheet">
<script src="https://code.highcharts.com/highcharts.src.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script></head>

<body> <!-- Add your content of header -->
<header>
  <nav class="navbar navbar-default active">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'conc:index' %}" title="">
          <img src="../../../static/images/mashup-icon.svg" class="navbar-logo-img" alt="">
          어디보냐
        </a>
      </div>

      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'conc:index' %}" title="">Home</a></li>
          <li><a href="{% url 'conc:project' %}" title="">집중도 측정</a></li>
          <li>
            <p>
              <a href="{% url 'common:logout' %}" class="btn btn-default navbar-btn" title="">로그아웃</a>
            </p>
          </li>

        </ul>
      </div> 
    </div>
  </nav>
</header>

<div class="section-container">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-md-8 col-md-offset-2">
          <h1 class="text-center">나의 점수는</h1>
          <div class="text-center">
            <b><br><br><br><br><br><br><br><br><br>측정 결과가 존재하지 않습니다.<br><br><br><br><br><br><br><br><br></b>
          </div>
       </div>
      </div>
    </div>
  </div>


<footer class="footer-container white-text-container">
  <div class="container">
    <div class="row">

     
      <div class="col-xs-12">
        <h3>INUIT</h3>

        <div class="row">
          <div class="col-xs-12 col-sm-7">
            <p><small>Capstone Design (2021-2022)</small>
            </p>
            <p><small>Website created with <a href="http://www.mashup-template.com/" title="Create website with free html template">Mashup Template</a>/<a href="https://www.unsplash.com/" title="Beautiful Free Images">Unsplash</a></small>
            </p>
          </div>
        </div>
        
        
      </div>
    </div>
  </div>
</footer>

<script>
  document.addEventListener("DOMContentLoaded", function (event) {
    navActivePage();
    scrollRevelation('.reveal');
  });
</script>

<!-- Google Analytics: change UA-XXXXX-X to be your site's ID 

<script>
  (function (i, s, o, g, r, a, m) {
    i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
      (i[r].q = i[r].q || []).push(arguments)
    }, i[r].l = 1 * new Date(); a = s.createElement(o),
      m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
  })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
  ga('create', 'UA-XXXXX-X', 'auto');
  ga('send', 'pageview');
</script>

--> <script type="text/javascript" src="../../../static/main.js"></script></body>

</html>